server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    name: ibookingdb
    url: jdbc:h2:~/mydb
    username: sa
    password: test123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver

  druid:
    validation-query: select 1
    test-on-borrow: false


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

mybatis:
  mapper-locations: classpath:com.huawei.ibooking.mapper/*.xml
  type-aliases-package: com.huawei.ibooking.model

logging:
  level:
    com.huawei.ibooking: debug
